#ifndef USER_LED_H_
#define USER_LED_H_

#include <stdint.h>

enum user_led_e
{
	USER_LED_L1 = 0,
	USER_LED_L2 = 1,
	USER_LED_L3 = 2,
	USER_LED_N = 3,
	USER_LED_PE = 4,
	USER_LED_TEMP = 5,
	USER_LED_NUM_OF,
};

enum user_led_type_e
{
	USER_LED_TYPE_RGB = 0, //RGB
	USER_LED_TYPE_RW, //red, white
};

enum user_led_color_e
{
	USER_LED_COLOR_NONE = 0,
	USER_LED_COLOR_RED,
	USER_LED_COLOR_GREEN,
	USER_LED_COLOR_BLUE,
	USER_LED_COLOR_WHITE,
};

enum user_led_states_e
{
	USER_LED_STATE_BOOT = 0,
	USER_LED_STATE_ROT_R,
	USER_LED_STATE_ROT_L,
	USER_LED_STATE_LOST,
	USER_LED_STATE_ATTENTION,
	USER_LED_STATE_ALLOFF,
	USER_LED_STATE_ALLON,
	USER_LED_STATE_LEDTEST,
};

enum
{
	USER_LED_LOST_L1_BITPOS    	= USER_LED_L1,
	USER_LED_LOST_L2_BITPOS    	= USER_LED_L2,
	USER_LED_LOST_L3_BITPOS    	= USER_LED_L3,
	USER_LED_LOST_N_BITPOS     	= USER_LED_N,
	USER_LED_LOST_PE_BITPOS    	= USER_LED_PE,
	USER_LED_LOST_TEMP_BITPOS 	= USER_LED_TEMP,
	USER_LED_UNKNOWN_L1_BITPOS 	= (USER_LED_L1 + 8),
	USER_LED_UNKNOWN_L2_BITPOS 	= (USER_LED_L2 + 8),
	USER_LED_UNKNOWN_L3_BITPOS 	= (USER_LED_L3 + 8),
	USER_LED_UNKNOWN_N_BITPOS  	= (USER_LED_N + 8),
	USER_LED_DIR_R_BITPOS		= (USER_LED_N + 1 + 8),
	USER_LED_DIR_L_BITPOS		= (USER_LED_N + 2 + 8),
};

enum
{
	USER_LED_LOST_NONE      = 0x0000,
	USER_LED_LOST_L1_BIT    = (1UL << USER_LED_LOST_L1_BITPOS),
	USER_LED_LOST_L2_BIT    = (1UL << USER_LED_LOST_L2_BITPOS),
	USER_LED_LOST_L3_BIT    = (1UL << USER_LED_LOST_L3_BITPOS),
	USER_LED_LOST_N_BIT     = (1UL << USER_LED_LOST_N_BITPOS),
	USER_LED_LOST_PE_BIT    = (1UL << USER_LED_LOST_PE_BITPOS),
	USER_LED_LOST_TEMP_BIT  = (1UL << USER_LED_LOST_TEMP_BITPOS),
	USER_LED_UNKNOWN_L1_BIT = (1UL << USER_LED_UNKNOWN_L1_BITPOS),
	USER_LED_UNKNOWN_L2_BIT = (1UL << USER_LED_UNKNOWN_L2_BITPOS),
	USER_LED_UNKNOWN_L3_BIT = (1UL << USER_LED_UNKNOWN_L3_BITPOS),
	USER_LED_UNKNOWN_N_BIT  = (1UL << USER_LED_UNKNOWN_N_BITPOS),
	USER_LED_DIR_R_BIT		= (1UL << USER_LED_DIR_R_BITPOS),
	USER_LED_DIR_L_BIT		= (1UL << USER_LED_DIR_L_BITPOS),
};

void user_led_init(void);
void user_led_start_heartbeatblink(int blinknum);
void user_led_set_state(enum user_led_states_e state, uint16_t lost_bitmask);
void user_led_set_color(enum user_led_e led, enum user_led_color_e color);

#endif /* USER_LED_H_ */
